name: flutter_dashboard
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'



dependencies:
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding
      path: plugins/window_size
  file_picker: ^5.5.0
  fl_chart: ^0.63.0
  flutter:
    sdk: flutter
  get_it: ^7.6.4
  shared_preferences: ^2.2.1
  syncfusion_flutter_charts: ^23.1.36
  syncfusion_localizations: ^23.1.36
  watcher: ^1.1.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    # Add assets from the images directory to the application.
    - assets/python/
    - assets/python/devdata/
    - assets/python/first_table/
    - assets/python/Platts/
    - assets/python/output/shared/workitems.json
