name: flutter_dashboard
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  dartz: ^0.10.1
  dio: ^5.3.3
  equatable: ^2.0.5
  excel: ^2.1.0
  file_picker: ^5.5.0
  fl_chart: ^0.63.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  get_it: ^7.6.4
  http: ^1.1.0
  shared_preferences: ^2.2.1
  syncfusion_flutter_charts: ^23.1.36
  syncfusion_localizations: ^23.1.36
  watcher: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    # Add assets from the images directory to the application.
    - assets/json/
    - assets/python/
    - assets/python/devdata/
    - assets/python/first_table/
    - assets/python/Platts/
    - assets/python/output/shared/workitems.json
